# Contenido de las guías Entalle. Solo hábitos generales: sin promesas de salud.
AVISO = ("Contenido informativo sobre hábitos generales. No reemplaza la indicación de un "
         "profesional de la salud. Si tienes una condición médica, estás embarazada, amamantando "
         "o tomas medicamentos, consulta antes de hacer cambios en tu rutina.")

GUIAS = {
 "habitos-21-dias": {
  "titulo": "21 días de hábitos simples",
  "kicker": "Guía Entalle",
  "sub": "Hidratación, mañanas, movimiento, alimentación y descanso: pequeños pasos que sí se mantienen.",
  "img": "clorofila.png", "img2": "aurelys.png", "img3": "neurazenx.png",
  "precio": 6990,
  "paginas": [
   ("intro", "Cómo usar esta guía", [
     ("p", "Esta guía no busca cambiar tu vida en un fin de semana. Busca algo más útil: que en 21 días tengas cinco hábitos simples funcionando casi en piloto automático."),
     ("p", "Cada capítulo trae una idea central, pasos concretos y un mini desafío. Al final encontrarás un plan de 21 días y una hoja para marcar tu avance."),
     ("box", "La regla de oro: empieza tan pequeño que sea imposible fallar. Un vaso de agua al despertar vale más que un plan perfecto que abandonas el martes."),
     ("h3", "Qué vas a trabajar"),
     ("ul", ["Hidratación a lo largo del día", "Una mañana de 10 minutos", "Moverte más, aunque trabajes sentado", "Un plato más equilibrado", "Dormir con horario"]),
   ]),
   ("cap", "Por qué 21 días", [
     ("p", "Un hábito es una acción que repites tantas veces que deja de requerir esfuerzo. No existe un número mágico de días, pero tres semanas son suficientes para notar que algo cambió y querer seguir."),
     ("h3", "Las 3 claves de un hábito que dura"),
     ("ol", ["<b>Anclarlo</b> a algo que ya haces: \"después de lavarme los dientes, tomo un vaso de agua\".",
             "<b>Hacerlo visible</b>: la botella en el escritorio, las zapatillas junto a la puerta.",
             "<b>Registrarlo</b>: marcar el día en la hoja de seguimiento es una pequeña recompensa."]),
     ("box", "Si fallas un día, no pasa nada. La regla es simple: nunca dos días seguidos."),
   ]),
   ("cap", "Hábito 1 · Hidratación", [
     ("p", "Muchas veces pasamos horas sin tomar agua simplemente porque no la tenemos a mano. La meta no es contar mililitros, sino que el agua esté presente durante todo tu día."),
     ("h3", "Pasos concretos"),
     ("ul", ["Un vaso de agua apenas te levantas, antes del café.", "Una botella reutilizable siempre a la vista.",
             "Un vaso de agua con cada comida.", "Si te aburre el agua sola, saborízala con rodajas de limón, pepino o menta.",
             "Tu orina clara es una buena señal de que vas bien."]),
     ("box", "Mini desafío: llena tu botella tres veces hoy. Marca cada recarga."),
   ]),
   ("cap", "Hábito 2 · Una mañana de 10 minutos", [
     ("p", "La forma en que empiezas el día influye en todo lo que viene después. No necesitas levantarte a las 5 a. m.: basta con 10 minutos intencionales."),
     ("h3", "Tu rutina base"),
     ("ol", ["<b>Agua</b>: un vaso grande al despertar.", "<b>Luz</b>: abre las cortinas o sal a la ventana 2 minutos.",
             "<b>Estira</b>: cuello, hombros y espalda, 3 minutos.", "<b>Desayuna</b> algo simple con proteína (huevo, yogur, pan integral con palta).",
             "<b>Planifica</b>: anota las 3 tareas más importantes del día."]),
     ("box", "Deja lista la noche anterior tu botella llena y lo que vas a desayunar. Así la mañana se hace sola."),
   ]),
   ("cap", "Hábito 3 · Moverte más", [
     ("p", "Si trabajas sentado o de pie muchas horas, el cuerpo agradece cualquier cambio de posición. No hace falta un gimnasio: hace falta interrumpir la quietud."),
     ("h3", "Ideas para tu día"),
     ("ul", ["Una pausa de 2 a 3 minutos cada hora: ponte de pie, camina, estírate.", "Camina 20 a 30 minutos al día, aunque sea en dos partes.",
             "Usa las escaleras cuando puedas.", "Habla por teléfono caminando.", "Al llegar a casa, 10 minutos con las piernas en alto y una caminata suave después de cenar."]),
     ("h3", "5 estiramientos de oficina"),
     ("ol", ["Círculos de tobillo: 10 por lado.", "Elevación de talones de pie: 15 repeticiones.", "Estiramiento de gemelos apoyado en la pared: 20 segundos por pierna.",
             "Rotación de hombros hacia atrás: 10 veces.", "Inclinación lateral de cuello: 15 segundos por lado."]),
   ]),
   ("cap", "Hábito 4 · Un plato más equilibrado", [
     ("p", "Comer mejor no significa hacer dieta. Una forma sencilla de ordenar tus comidas es pensar en el plato."),
     ("h3", "El plato simple"),
     ("ul", ["<b>La mitad</b>: verduras de cualquier color, crudas o cocidas.", "<b>Un cuarto</b>: proteína (pollo, pescado, huevo, legumbres, carne magra).",
             "<b>Un cuarto</b>: carbohidratos (arroz, papas, pasta, pan integral).", "<b>Un toque</b> de grasa buena: palta, aceite de oliva, frutos secos."]),
     ("h3", "Pequeños cambios que suman"),
     ("ul", ["Fíjate en los sellos \"ALTO EN\" de los envases y elige la opción con menos sellos.", "Ten fruta lavada a la vista para el antojo de la tarde.",
             "Cocina doble y guarda una porción para el día siguiente.", "Come sin pantalla al menos una comida al día."]),
   ]),
   ("cap", "Hábito 5 · Dormir con horario", [
     ("p", "Descansar bien es la base de todo lo demás. El truco más efectivo es también el más simple: acostarte y levantarte a la misma hora, incluso el fin de semana."),
     ("h3", "Tu rutina de noche"),
     ("ul", ["Deja las pantallas 30 a 60 minutos antes de dormir.", "Evita el café y las bebidas con cafeína después de media tarde.",
             "Mantén tu pieza oscura, fresca y en silencio.", "Cena liviano y al menos dos horas antes de acostarte.", "Anota en un papel lo pendiente para mañana y suéltalo."]),
     ("box", "Mini desafío: pon una alarma que te avise la hora de empezar a desconectarte."),
   ]),
   ("plan", "Tu plan de 21 días", [
     ("week", "Semana 1 · Base", ["Vaso de agua al despertar", "Botella siempre a la vista", "Mañana de 10 minutos"]),
     ("week", "Semana 2 · Movimiento", ["Todo lo de la semana 1", "Pausa activa cada hora", "Caminata de 20 minutos"]),
     ("week", "Semana 3 · Equilibrio", ["Todo lo anterior", "Un plato equilibrado al día", "Horario fijo para dormir"]),
     ("box", "Al terminar, repite la semana que más te costó. Los hábitos se construyen con repetición, no con perfección."),
   ]),
   ("tracker", "Hoja de seguimiento", {"dias": 21, "filas": ["Agua al despertar", "Botella a la vista", "Mañana de 10 min", "Pausas activas", "Caminata", "Plato equilibrado", "Horario de sueño"]}),
   ("productos", "Complementa tu rutina", [
     ("p", "En Entalle elegimos productos que calzan con una rutina simple y constante. Úsalos siempre según las indicaciones de su envase."),
     ("prod", "clorofila.png", "Clorofila líquida Benevolent", "Unas gotas en tu botella de agua. Sabor menta, sin alcohol y sin gluten."),
     ("prod", "aurelys.png", "Aurelys Drenaje Linfático", "Suplemento herbal en gotas para sumar a tu mañana, en agua o té."),
     ("prod", "neurazenx.png", "NeuraZenx Ácido Alfa Lipoico 600 mg", "Cápsulas vegetales con Bioperine para tu consumo diario."),
   ]),
  ],
 },
 "hidratacion-rutina-verde": {
  "titulo": "Hidratación y rutina verde",
  "kicker": "Guía Entalle · Clorofila",
  "sub": "Ideas simples para tomar más agua, 8 aguas saborizadas y tu rutina diaria con clorofila.",
  "img": "clorofila.png", "precio": 4990,
  "paginas": [
   ("intro", "Tu agua, pero con algo más", [
     ("p", "Tomar agua suficiente es uno de los hábitos más simples y a la vez más olvidados. Esta guía te ayuda a que el agua esté presente en tu día sin que tengas que pensarlo."),
     ("h3", "En esta guía"),
     ("ul", ["10 trucos para tomar más agua", "8 aguas saborizadas fáciles", "Cómo sumar la clorofila a tu rutina", "Un plan de 7 días y tu hoja de seguimiento"]),
   ]),
   ("cap", "10 trucos para tomar más agua", [
     ("ol", ["Un vaso grande apenas te levantas.", "Botella reutilizable siempre a la vista.", "Un vaso con cada comida.",
             "Pon alarmas suaves a media mañana y media tarde.", "Usa una botella con marcas de horario.", "Saborízala con fruta, hierbas o unas gotas de clorofila.",
             "Toma un vaso cada vez que vuelvas a tu escritorio.", "Prefiere agua en vez de bebidas azucaradas.", "Lleva agua cuando salgas, aunque sea un trámite corto.",
             "Registra tus vasos del día en la hoja de seguimiento."]),
     ("box", "¿Cuánta agua? Depende de cada persona, del clima y de tu actividad. Una referencia común es de 6 a 8 vasos al día; escucha tu sed y ajusta."),
   ]),
   ("recetas", "8 aguas saborizadas", [
     ("rec", "Pepino y menta", "Medio pepino en rodajas y unas hojas de menta en 1 litro de agua fría."),
     ("rec", "Limón y jengibre", "Rodajas de medio limón y una lámina de jengibre fresco."),
     ("rec", "Frutilla y albahaca", "5 frutillas en mitades y 4 hojas de albahaca."),
     ("rec", "Naranja y canela", "Rodajas de una naranja y una rama de canela."),
     ("rec", "Piña y menta", "Trozos de piña fresca y unas hojas de menta."),
     ("rec", "Manzana y canela", "Láminas finas de manzana verde y una rama de canela."),
     ("rec", "Frambuesa y limón", "Un puñado de frambuesas y rodajas de limón."),
     ("rec", "Sandía y menta", "Cubos de sandía y menta; ideal para días de calor."),
     ("box", "Deja reposar en el refrigerador 1 a 2 horas. Consúmelas dentro de 24 horas."),
   ]),
   ("cap", "Tu rutina verde con clorofila", [
     ("p", "La clorofila líquida Benevolent tiene sabor menta y se agrega directo al agua. Es una forma práctica de hacer más atractiva tu botella del día."),
     ("h3", "Cómo incorporarla"),
     ("ol", ["Agita el frasco antes de usar.", "Agrega a tu vaso o botella la cantidad indicada en la etiqueta.", "Mezcla y disfrútala fresca, con hielo si quieres.",
             "Elige un momento fijo: al despertar o al llegar al trabajo."]),
     ("box", "Tip: combina la clorofila con el agua de pepino y menta. Queda fresca y muy verde."),
     ("img", "clorofila.png"),
   ]),
   ("plan", "Plan de 7 días", [
     ("week", "Días 1 y 2", ["Vaso al despertar", "Botella a la vista"]),
     ("week", "Días 3 y 4", ["Lo anterior", "Un agua saborizada al día"]),
     ("week", "Días 5 a 7", ["Lo anterior", "Clorofila en tu botella de la mañana", "Marca tus vasos"]),
   ]),
   ("tracker", "Seguimiento de vasos", {"dias": 7, "filas": ["Vaso 1", "Vaso 2", "Vaso 3", "Vaso 4", "Vaso 5", "Vaso 6", "Vaso 7", "Vaso 8"]}),
  ],
 },
 "guia-dias-largos": {
  "titulo": "Guía para días largos",
  "kicker": "Guía Entalle · Aurelys",
  "sub": "Pausas activas, hábitos para jornadas sentado o de pie y una rutina de mañana y noche.",
  "img": "aurelys.png", "precio": 4990,
  "paginas": [
   ("intro", "Tu día pesa. Tu rutina, no.", [
     ("p", "Ocho horas en una silla, en una caja o de pie en un local se sienten al final del día. Esta guía reúne hábitos simples para cuidar tu cuerpo durante jornadas largas."),
     ("h3", "En esta guía"),
     ("ul", ["Pausas activas para hacer en 3 minutos", "Consejos si trabajas sentado o de pie", "Qué hacer al llegar a casa", "Tu rutina de mañana con Aurelys", "Plan semanal y hoja de seguimiento"]),
   ]),
   ("cap", "Pausas activas de 3 minutos", [
     ("p", "La clave no es hacer mucho, sino cortar la quietud. Programa una alarma cada 60 minutos y elige 2 o 3 de estos movimientos."),
     ("ol", ["<b>Círculos de tobillo</b>: sentado, 10 círculos por pie en cada sentido.", "<b>Puntas y talones</b>: de pie, sube a la punta de los pies y baja lento, 15 veces.",
             "<b>Marcha en el lugar</b>: 1 minuto, subiendo las rodillas.", "<b>Gemelos a la pared</b>: una pierna atrás, talón al suelo, 20 segundos por lado.",
             "<b>Hombros y cuello</b>: 10 rotaciones hacia atrás y 15 segundos de inclinación por lado."]),
     ("box", "Si alguno de estos movimientos te molesta, detente. Muévete siempre dentro de tu comodidad."),
   ]),
   ("cap", "Si trabajas sentado o de pie", [
     ("h3", "Sentado"),
     ("ul", ["Apoya ambos pies en el suelo; si no alcanzas, usa un reposapiés.", "Evita cruzar las piernas por mucho rato.", "Levántate a buscar agua: hidratación y pausa en un solo gesto."]),
     ("h3", "De pie"),
     ("ul", ["Alterna el peso entre una pierna y otra.", "Usa calzado cómodo y con buen soporte.", "Aprovecha cualquier momento para sentarte o caminar un poco."]),
     ("h3", "Siempre"),
     ("ul", ["Toma agua durante la jornada.", "Modera la sal y los ultraprocesados en tus colaciones.", "Prefiere ropa que no apriete."]),
   ]),
   ("cap", "Al llegar a casa", [
     ("ol", ["<b>10 a 15 minutos con las piernas en alto</b>, apoyadas en la pared o en cojines.", "<b>Una ducha</b> tibia terminando con agua más fresca en las piernas.",
             "<b>Caminata suave</b> de 10 minutos después de cenar.", "<b>Cena liviana</b>, con verduras y agua.", "<b>A dormir con horario</b>: tu cuerpo lo agradece al día siguiente."]),
   ]),
   ("cap", "Tu rutina de mañana con Aurelys", [
     ("p", "Aurelys Drenaje Linfático es un suplemento herbal en gotas. Sumarlo a tu mañana es tan simple como agregarlo a tu agua o té."),
     ("ol", ["Agita el frasco.", "Mide la porción indicada en la etiqueta con el gotario.", "Tómalo en agua, en té o bajo la lengua.", "Hazlo siempre en el mismo momento del día."]),
     ("box", "Combínalo con tu vaso de agua al despertar y tus 3 minutos de estiramiento: en 5 minutos tienes una mañana completa."),
     ("img", "aurelys.png"),
   ]),
   ("plan", "Plan semanal", [
     ("week", "Lunes a viernes", ["Mañana: agua + Aurelys + estiramiento", "Jornada: pausa activa cada hora", "Noche: piernas en alto 10 minutos"]),
     ("week", "Fin de semana", ["Caminata de 30 minutos", "Prepara colaciones para la semana", "Mismo horario de sueño"]),
   ]),
   ("tracker", "Seguimiento semanal", {"dias": 14, "filas": ["Rutina de mañana", "Pausas activas", "Agua durante la jornada", "Piernas en alto", "Caminata"]}),
  ],
 },
 "constancia-energia-diaria": {
  "titulo": "Constancia y energía diaria",
  "kicker": "Guía Entalle · NeuraZenx",
  "sub": "Cómo sostener un hábito, dormir mejor, comer simple y organizar una semana con más energía.",
  "img": "neurazenx.png", "precio": 4990,
  "paginas": [
   ("intro", "La constancia le gana a la intensidad", [
     ("p", "Los resultados de cualquier hábito, desde caminar hasta tomar un suplemento, dependen de algo muy simple: hacerlo todos los días. Esta guía te ayuda a que eso pase."),
     ("h3", "En esta guía"),
     ("ul", ["Cómo no olvidar tu rutina diaria", "Sueño y luz: la base de la energía", "Alimentación simple para el día a día", "Pausas para bajar el estrés", "Plan semanal y seguimiento de 30 días"]),
   ]),
   ("cap", "Cómo no olvidar tu rutina", [
     ("ol", ["<b>Ánclala</b> a algo fijo: el desayuno o el vaso de agua de la mañana.", "<b>Deja el frasco a la vista</b>, junto a tu taza o tu botella.",
             "<b>Pon una alarma</b> los primeros 14 días.", "<b>Marca cada día</b> en la hoja de seguimiento.", "<b>Ten un respaldo</b>: si viajas, lleva las cápsulas del día en un pastillero."]),
     ("box", "NeuraZenx se toma siempre según la dosis indicada en el envase, con un vaso de agua."),
     ("img", "neurazenx.png"),
   ]),
   ("cap", "Sueño y luz: la base", [
     ("ul", ["Acuéstate y levántate a la misma hora, también el fin de semana.", "Recibe luz natural en la mañana: 10 minutos al aire libre o junto a una ventana.",
             "Evita pantallas 30 a 60 minutos antes de dormir.", "Deja el café para la mañana.", "Si te cuesta dormir, prueba leer papel o escuchar algo tranquilo."]),
   ]),
   ("cap", "Alimentación simple", [
     ("ul", ["Incluye proteína en cada comida: huevo, legumbres, pescado, pollo, yogur.", "Suma verduras de colores en almuerzo y cena.",
             "Grasas buenas: palta, aceite de oliva, nueces y almendras.", "Toma agua durante el día; muchas veces el cansancio de la tarde coincide con poca hidratación.",
             "Colaciones simples: fruta, frutos secos o un yogur, en vez de galletas."]),
     ("box", "Mira los sellos \"ALTO EN\" y elige la opción con menos sellos cuando puedas."),
   ]),
   ("cap", "Pausas para bajar el estrés", [
     ("h3", "Respiración 4-4-6"),
     ("p", "Inhala por la nariz contando hasta 4, sostén 4 y bota el aire lento por la boca contando hasta 6. Repite 5 veces."),
     ("h3", "Otras pausas"),
     ("ul", ["Camina 5 minutos sin el celular.", "Estira cuello y hombros.", "Anota lo que te preocupa y una acción pequeña para mañana.", "Una conversación corta con alguien que te haga reír."]),
   ]),
   ("plan", "Tu semana", [
     ("week", "Cada mañana", ["Agua + NeuraZenx según el envase", "10 minutos de luz natural", "Desayuno con proteína"]),
     ("week", "Durante el día", ["Pausa de respiración", "Caminata de 20 minutos", "Colación simple"]),
     ("week", "Cada noche", ["Pantallas fuera 30 minutos antes", "Mismo horario de sueño"]),
   ]),
   ("tracker", "Seguimiento de 30 días", {"dias": 30, "filas": ["Rutina de la mañana", "Luz natural", "Caminata", "Horario de sueño"]}),
  ],
 },
}
